export const UI_TEXT = {
  global: {
    title: "MUSIC TOOLS STUDIO",
    subtitle: "Professional Analog Audio Processor Rack",
    intro: "支援本機高品質音訊轉檔、YouTube 提取、人聲/伴奏分離、樂器多軌分離與移調變速。所有運算皆在您的 Mac 上安全執行，同個 Wi-Fi 下的手機亦可直接瀏覽使用。",
    apiBase: "API 節點: ",
    emptyRackSlot: "EMPTY CHANNEL - OFFLINE",
  },
  powerPanel: {
    title: "CONSOLE ROUTING & POWER DISTRIBUTION",
    wavToggle: "POWER",
    ytToggle: "BUS 1",
    vocalToggle: "BUS 2",
    stemsToggle: "BUS 3",
    pitchToggle: "BUS 4",
  },
  wavConverter: {
    title: "WAV TO MP3",
    desc: "將無損 WAV 快速轉為 320kbps MP3。",
    dragPrompt: "拖曳 WAV 檔案至此",
    buttonStart: "開始轉檔",
    buttonBusy: "建立任務中...",
  },
  ytExtractor: {
    title: "YOUTUBE TO MP3",
    desc: "貼上 YT 網址提取並下載高音質 MP3。",
    placeholder: "貼上 https://www.youtube.com/watch?v=...",
    buttonStart: "提取並轉檔",
    buttonBusy: "建立任務中...",
  },
  vocalSeparator: {
    title: "VOCAL SEPARATOR",
    desc: "使用 Demucs ft 模型分離人聲與伴奏。",
    dragPrompt: "拖曳音訊檔至此",
    buttonStart: "開始分離",
    buttonBusy: "建立任務中...",
  },
  stemsSeparator: {
    title: "STEMS SEPARATOR",
    desc: "分離人聲、鼓、貝斯、吉他與鋼琴。薩克斯風可以勾選「other其他樂器」試試看！",
    qualityLabel: "分離品質",
    selectAll: "全選",
    clearAll: "清除",
    selectedStems: "已選軌道：",
    noneSelected: "尚未選擇",
    dragPrompt: "拖曳音訊檔至此",
    buttonStart: "開始多軌分離",
    buttonBusy: "建立任務中...",
  },
  pitch: {
    title: "PITCH & TEMPO",
    desc: "分析並調整音訊的半音數或目標 BPM。",
    dragPrompt: "拖曳音訊檔至此",
    buttonAnalyze: "⚡ 分析調性與 BPM",
    buttonAnalyzing: "分析中...",
    keyCurrent: "目前調性 Key",
    keyAdjusted: "移調後調性",
    bpmOriginal: "原始 BPM",
    bpmTarget: "目標 BPM",
    semitonesLabel: "移調半音 (Semitones)：",
    bpmLabel: "設定目標 BPM",
    buttonStart: "開始處理並輸出",
    notAnalyzed: "尚未分析",
    notSet: "尚未設定",
  },
  status: {
    title: "MONITOR / LCD STATUS PANEL",
    labelState: "目前狀態",
    labelJobId: "任務 ID",
    labelOutputFile: "輸出檔案",
    labelProgress: "進度：",
    downloadZip: "下載 ZIP 打包檔",
    downloadMp3: "下載 MP3 音訊檔",
    noJob: "SYSTEM READY / IDLE",
    adLabel: "SPONSOR ADVERTISEMENT",
  }
};
